### ISSUE TITLE
rename_files does not support movie formats

### ISSUE THREAD

**Issue by klutchell** [Kameecoding/conv2mp4-py#1]
In the latest master, the rename_files function assumes a tv format whether we are processing movies or not. The attached patch adds better movie support to the rename_files function.
[ac829303cff2d35b6ade6c0cdc0553d7888ce0d4.zip](https://github.com/Kameecoding/conv2mp4-py/files/435193/ac829303cff2d35b6ade6c0cdc0553d7888ce0d4.zip)

**Comment by klutchell** [comment]
Commit 692062aefe8a76bf1ac6a0aca33a3786e4c0311f resolves part of this by using the {plex} format. Still the check at the beginning needs to be adjusted to check for already renamed movies.

**Comment by Kameecoding** [comment]
merched pull request #2, closing this one.
